# Generated by Django 3.1.7 on 2021-05-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210524_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='products/no_pic.jpg', upload_to='products'),
        ),
    ]
