# Generated by Django 3.1.7 on 2021-06-08 23:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='products', validators=[account.models.validate_image]),
        ),
    ]
