# Generated by Django 3.1.7 on 2021-05-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210524_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
