# Generated by Django 3.1.7 on 2021-06-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
