# Generated by Django 3.1.7 on 2021-06-15 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_product_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999'. Up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
