# Generated by Django 3.1.7 on 2021-05-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_sum',
            field=models.FloatField(null=True),
        ),
    ]
