# Generated by Django 3.1.7 on 2021-06-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='account.Tag'),
        ),
    ]
